[project]
name = "duckdb-threads"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.0",
    "gradio>=5.45.0",
    "jupyter>=1.1.1",
    "plotly>=6.3.0",
]
